#!/usr/bin/env python3
"""Regenerate lib/utils/fa7_solid_map.dart from font_awesome_flutter.

Reads the package's generated icon class (FontAwesomeIcons, FA 7.2.0 solid)
from the pub cache, kebab-cases each name, and emits a const name->IconData
map. The const map doubles as the release icon tree-shake keep-list: every
glyph the app can render is referenced as a constant, so no glyph gets
stripped from the bundled font and server-sent codepoints render at runtime.

Run after bumping font_awesome_flutter. Output is ASCII-only.

Usage: python3 tool/gen_fa7_icon_map.py
"""

import os
import re
import sys

HOME = os.path.expanduser("~")
PKG = os.path.join(
    HOME,
    ".pub-cache/hosted/pub.dev/font_awesome_flutter-11.0.0/lib/font_awesome_flutter.dart",
)
OUT = os.path.join(os.path.dirname(__file__), "..", "lib", "utils", "fa7_solid_map.dart")


def kebab(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def main() -> int:
    if not os.path.exists(PKG):
        print(f"font_awesome_flutter source not found: {PKG}", file=sys.stderr)
        return 1

    src = open(PKG, encoding="utf-8").read()
    pairs = re.findall(
        r"static const FaIconData (\w+) = FaIconData\(\s*IconData\(\s*0x([0-9a-fA-F]+),\s*fontFamily: '(\w+)'",
        src,
    )
    # Solid family only: brand/regular glyphs live in other fonts, and the
    # site's picker catalog is capped to the solid font anyway.
    solid = [(n, int(c, 16)) for n, c, fam in pairs if fam == "FontAwesomeSolid"]
    if not solid:
        print("no solid icons parsed (pattern changed?)", file=sys.stderr)
        return 1

    # Multi-style icons: the plain name is the REGULAR variant (addressBook,
    # bell, clock...) and the solid one is prefixed (solidAddressBook, ...).
    # The site's fa-* names refer to the solid glyph, so key the prefixed
    # entries under the stripped name: solidAddressBook -> fa-address-book.
    # Strip only when the plain counterpart is non-solid (solidA is a real
    # solid-only icon; 'a' must stay fa-a, not collide).
    fam_of = {n: fam for n, _, fam in pairs}
    entries = []
    for raw, code in sorted(solid, key=lambda p: p[1]):
        if raw.startswith("solid") and raw[5:] and raw[5:] not in fam_of:
            plain = raw[5].lower() + raw[6:]
            if fam_of.get(plain) not in (None, "FontAwesomeSolid"):
                raw = plain
        entries.append(
            f"  'fa-{kebab(raw)}': FaIconData(IconData(0x{code:X}, "
            "fontFamily: 'FontAwesomeSolid', fontPackage: 'font_awesome_flutter')),"
        )
    # Key collision check (a stripped name must never clash with a plain one).
    keys = [e.split("':")[0].strip() for e in entries]
    dups = {k for k in keys if keys.count(k) > 1}
    if dups:
        print("DUPLICATE KEYS:", sorted(dups), file=sys.stderr)
        return 1

    body = f"""// GENERATED by tool/gen_fa7_icon_map.py from font_awesome_flutter
// 11.0.0 (Font Awesome 7.2.0 solid set). Do not hand-edit; rerun the
// script after a package bump. Const references keep every glyph in the
// release icon font (tree-shake keep-list).

import 'package:flutter/widgets.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

/// fa-* class name -> solid icon, full FA7 set ({len(solid)} icons).
const Map<String, FaIconData> kFa7Solid = {{
{chr(10).join(entries)}
}};
"""
    with open(OUT, "w", encoding="ascii", newline="\n") as f:
        f.write(body)
    print(f"wrote {OUT}: {len(pairs)} icons")
    return 0


if __name__ == "__main__":
    sys.exit(main())
